import { createContext } from "react";

export const FormContext = createContext({
  divisions: ["Kontrol", "Mekanik", "Official", "Both", "All"],
  roles: [
    "Ketua",
    "Wakil Ketua",
    "Manpro R1",
    "Manpro R2",
    "Kepala Divisi Mekanik",
    "Kepala Divisi Kontrol",
    "Kru Mekanik",
    "Kru Kontrol",
    "Official",
  ],
  generations: [13, 14, 15],
  genderIdentities: [
  "Male",
  "Female",
  "Non-binary",
  "Genderqueer",
  "Genderfluid",
  "Agender",
  "Bigender",
  "Two-spirit",
  "Demiboy",
  "Demigirl",
  "Androgynous",
  "Neutrois",
  "Pangender",
  "Third gender",
  "Bi-gender",
  "Fluidflux",
  "Multigender",
  "Hijra",
  "Kathoey",
  "Femme",
  "Butch",
  "Two-spirit",
  "X-gender",
  "Other",
  // Add more as needed
],
});
